spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: CLIENT-SERVICE
  application:
    name: CLIENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/clientdb?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always


